vae_opt= {
    'dataset':'celebA',
    'spread': False,
    'image_dim': 64,
    'channels': 3,
    'all_pic_dim': 12288,
    'x_dim': 12288,
    'dis': 'gauss',
    'batch_size': 64,
    'noise_rank': 1,
    'training_epoch':100,
    'noise_epoch': 0,
    'num_units': 1024,
    'encoder_layers': 4,
    'decoder_layers': 4,
    'kl_lr': 1e-4,
    'noise_lr': 1e-4,
    'z_dim': 64,
    'kl_sgx': 0.5,
    'restore': False,
    'path': '../result/celeba_vae/',
    'work_dir': '../result/celeba_vae/',
    'data_dir': '../../data/CelebA/images',
    'annealing': False,
    'low_variance': True,
    'noise_learning_period':10,
    'celebA_crop' : 'closecrop',
    'input_normalize_sym':False
}

vae_init_opt= {
    'save': True,
    'save_epoch': [1,100,200],
    'dataset': 'celebA',
    'spread': False,
    'image_dim': 64,
    'channels': 3,
    'all_pic_dim': 12288,
    'x_dim': 12288,
    'dis': 'gauss',
    'batch_size': 64,
    'noise_rank': 1,
    'training_epoch':200,
    'noise_epoch': 0,
    'num_units': 1024,
    'encoder_layers': 4,
    'decoder_layers': 4,
    'lr_decay': False,
    'decay_period': 30000,
    'decay_rate': 0.9,
    'kl_lr': 1e-4,
    'noise_lr': 1e-4,
    'z_dim': 64,
    'kl_sgx': 0.5,
    'restore': False,
    'noise_start_epoch': 100,
    'restore_path': '../result/celeba_vae_init/',
    'path': '../result/celeba_vae_init/',
    'work_dir': '../result/celeba_vae_init/',
    'data_dir': '../../data/CelebA/images',
    'annealing': False,
    'low_variance': True,
    'noise_learning_period':10,
    'celebA_crop': 'closecrop',
    'input_normalize_sym': False
}

vae_01_opt= {
    'save': True,
    'save_epoch': [1,100],
    'dataset': 'celebA',
    'spread': False,
    'image_dim': 64,
    'channels': 3,
    'all_pic_dim': 12288,
    'x_dim': 12288,
    'dis': 'gauss',
    'batch_size': 64,
    'noise_rank': 1,
    'training_epoch':100,
    'noise_epoch': 0,
    'num_units': 1024,
    'encoder_layers': 4,
    'decoder_layers': 4,
    'lr_decay': False,
    'decay_period': 30000,
    'decay_rate': 0.9,
    'kl_lr': 1e-4,
    'noise_lr': 1e-4,
    'z_dim': 64,
    'kl_sgx': 0.1,
    'restore': False,
    'noise_start_epoch': 100,
    'restore_path': '../result/celeba_vae_01/',
    'path': '../result/celeba_vae_01/',
    'work_dir': '../result/celeba_vae_01/',
    'data_dir': '../../data/CelebA/images',
    'annealing': False,
    'low_variance': True,
    'noise_learning_period':10,
    'celebA_crop': 'closecrop',
    'input_normalize_sym': False
}



vae_sq_opt= {
    'save': True,
    'save_epoch': [1,100],
    'dataset': 'celebA',
    'spread': False,
    'image_dim': 64,
    'channels': 3,
    'all_pic_dim': 12288,
    'x_dim': 12288,
    'dis': 'gauss',
    'batch_size': 64,
    'noise_rank': 1,
    'training_epoch':100,
    'noise_epoch': 0,
    'num_units': 1024,
    'encoder_layers': 4,
    'decoder_layers': 4,
    'lr_decay': False,
    'decay_period': 30000,
    'decay_rate': 0.9,
    'kl_lr': 1e-4,
    'noise_lr': 1e-4,
    'z_dim': 64,
    'kl_sgx': 0.72,
    'restore': False,
    'noise_start_epoch': 100,
    'path': '../result/celeba_sq_vae/',
    'work_dir': '../result/celeba_sq_vae/',
    'data_dir': '../../data/CelebA/images',
    'data_dir': '../../data/CelebA/images',
    'annealing': False,
    'low_variance': True,
    'noise_learning_period':10,
    'celebA_crop': 'closecrop',
    'input_normalize_sym': False
}
